### ISSUE TITLE
Failing to build the bindings

### ISSUE THREAD

**Issue by AregevDev** [pi-pi3/julia-rs#1]
It's just crashing with output:
error: failed to run custom build command for `julia-sys v0.2.0`
process didn't exit successfully: `/home/aregedev/IdeaProjects/rust_stuff/target/debug/build/julia-sys-641d9501cb483153/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-lib=julia

--- stderr
/usr/include/clang/6.0.0/include/emmintrin.h:2280:66: error: cannot convert between vector values of different size ('__v16hu' (vector of 16 'unsigned short' values) and 'int')
/usr/include/clang/6.0.0/include/emmintrin.h:2304:64: error: cannot convert between vector values of different size ('__v8su' (vector of 8 'unsigned int' values) and 'int')
/usr/include/clang/6.0.0/include/avx2intrin.h:151:66: error: cannot convert between vector values of different size ('__v32hu' (vector of 32 'unsigned short' values) and 'int')
/usr/include/clang/6.0.0/include/avx2intrin.h:161:66: error: cannot convert between vector values of different size ('__v16su' (vector of 16 'unsigned int' values) and 'int')
/usr/include/clang/6.0.0/include/fmaintrin.h:49:10: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size
/usr/include/clang/6.0.0/include/fmaintrin.h:55:10: error: invalid conversion between vector type '__m128d' (vector of 2 'double' values) and integer type 'int' of different size
/usr/include/clang/6.0.0/include/fmaintrin.h:73:10: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size
/usr/include/clang/6.0.0/include/fmaintrin.h:79:10: error: invalid conversion between vector type '__m128d' (vector of 2 'double' values) and integer type 'int' of different size
/usr/include/clang/6.0.0/include/fmaintrin.h:97:10: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size
/usr/include/clang/6.0.0/include/fmaintrin.h:103:10: error: invalid conversion between vector type '__m128d' (vector of 2 'double' values) and integer type 'int' of different size
/usr/include/clang/6.0.0/include/fmaintrin.h:121:10: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size
/usr/include/clang/6.0.0/include/fmaintrin.h:127:10: error: invalid conversion between vector type '__m128d' (vector of 2 'double' values) and integer type 'int' of different size
/usr/include/clang/6.0.0/include/avx512fintrin.h:1523:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
/usr/include/clang/6.0.0/include/avx512fintrin.h:1545:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
/usr/include/clang/6.0.0/include/avx512fintrin.h:5358:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
/usr/include/clang/6.0.0/include/avx512fintrin.h:5379:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
/usr/include/clang/6.0.0/include/avx512fintrin.h:5401:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
/usr/include/clang/6.0.0/include/avx512fintrin.h:5422:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
/usr/include/clang/6.0.0/include/avx512fintrin.h:5916:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
fatal error: too many errors emitted, stopping now [-ferror-limit=]
/usr/include/clang/6.0.0/include/emmintrin.h:2280:66: error: cannot convert between vector values of different size ('__v16hu' (vector of 16 'unsigned short' values) and 'int'), err: true
/usr/include/clang/6.0.0/include/emmintrin.h:2304:64: error: cannot convert between vector values of different size ('__v8su' (vector of 8 'unsigned int' values) and 'int'), err: true
/usr/include/clang/6.0.0/include/avx2intrin.h:151:66: error: cannot convert between vector values of different size ('__v32hu' (vector of 32 'unsigned short' values) and 'int'), err: true
/usr/include/clang/6.0.0/include/avx2intrin.h:161:66: error: cannot convert between vector values of different size ('__v16su' (vector of 16 'unsigned int' values) and 'int'), err: true
/usr/include/clang/6.0.0/include/fmaintrin.h:49:10: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size, err: true
/usr/include/clang/6.0.0/include/fmaintrin.h:55:10: error: invalid conversion between vector type '__m128d' (vector of 2 'double' values) and integer type 'int' of different size, err: true
/usr/include/clang/6.0.0/include/fmaintrin.h:73:10: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size, err: true
/usr/include/clang/6.0.0/include/fmaintrin.h:79:10: error: invalid conversion between vector type '__m128d' (vector of 2 'double' values) and integer type 'int' of different size, err: true
/usr/include/clang/6.0.0/include/fmaintrin.h:97:10: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size, err: true
/usr/include/clang/6.0.0/include/fmaintrin.h:103:10: error: invalid conversion between vector type '__m128d' (vector of 2 'double' values) and integer type 'int' of different size, err: true
/usr/include/clang/6.0.0/include/fmaintrin.h:121:10: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size, err: true
/usr/include/clang/6.0.0/include/fmaintrin.h:127:10: error: invalid conversion between vector type '__m128d' (vector of 2 'double' values) and integer type 'int' of different size, err: true
/usr/include/clang/6.0.0/include/avx512fintrin.h:1523:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
/usr/include/clang/6.0.0/include/avx512fintrin.h:1545:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
/usr/include/clang/6.0.0/include/avx512fintrin.h:5358:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
/usr/include/clang/6.0.0/include/avx512fintrin.h:5379:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
/usr/include/clang/6.0.0/include/avx512fintrin.h:5401:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
/usr/include/clang/6.0.0/include/avx512fintrin.h:5422:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
/usr/include/clang/6.0.0/include/avx512fintrin.h:5916:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
fatal error: too many errors emitted, stopping now [-ferror-limit=], err: true
thread 'main' panicked at 'Unable to generate bindings: ()', libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:476
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
             at libcore/macros.rs:26
   9: <core::result::Result<T, E>>::expect
             at libcore/result.rs:835
  10: build_script_build::main
             at ./build.rs:12
  11: std::rt::lang_start::{{closure}}
             at libstd/rt.rs:74
  12: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  13: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  14: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  15: std::rt::lang_start
             at libstd/rt.rs:74
  16: main
  17: __libc_start_main
  18: _start

Using the x86_64-unknown-linux-gnu toolchain

**Comment by pi-pi3** [comment]
This project has been stale for a while, but I'll see what I can do about it

**Comment by gnzlbg** [comment]
I'm seeing this same issue when building sleef-sys.

**Comment by AregevDev** [comment]
Working on a more stable version of the bindings, based on this API? Is this alright?

**Comment by pi-pi3** [comment]
This is more then alright, it's fantastic. Could you please link the repo in this issue?

**Comment by AregevDev** [comment]
Sorry, I was busy with studies, will start in the weekend I guess
